# Generated by Django 4.2.6 on 2023-10-11 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ordersell_warehouse_warehouseproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersell',
            old_name='warehouse',
            new_name='Warehouse',
        ),
        migrations.RemoveField(
            model_name='ordersell',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordersell',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ordersell',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.CreateModel(
            name='OrderSellProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordersell')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='ordersell',
            name='products',
            field=models.ManyToManyField(through='api.OrderSellProduct', to='api.product'),
        ),
    ]
