# Generated by Django 4.2.6 on 2023-10-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_warehouse_ordersell_warehouse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersell',
            old_name='Warehouse',
            new_name='warehouse',
        ),
    ]
